[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[context.production.environment]
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
    paths = [
      "node_modules",
      "package-lock.json",
      "dist"
    ]
